### ISSUE TITLE
32 bit version??

### ISSUE THREAD

**Issue by SolDev69** [MrPurple666/freedreno-CI#1]
PojavLauncher gonna use this and if there's no 32bit (armhf) version zink renderer will pretty much be 64bit only.

**Comment by MrPurple666** [comment]
> PojavLauncher gonna use this and if there's no 32bit (armhf) version zink renderer will pretty much be 64bit only.

It's possible I think, at least the vulkan library in armhf, I have no idea about zink as the CI is only for vulkan; feel free to fork and pull request with the changes.
